baseURL = "https://tedmoore.github.io"
languageCode = 'en-us'
title = "Ted Moore | Composer, Improviser, Intermedia Artist"
copyright = "Ted Moore. All Rights Reserved."
theme = ["gohugo-theme-ananke"]

[pagination]
  pagerSize = 10

[params]
  menu_classes = 'system sans-serif'
  body_classes = 'avenir next'
  post_content_classes = 'avenir next'
  env = "production"

[[params.works_media]]
  name = "saccades"
  id = "FN71qPEhnyo"
  type = "youtube"
[[params.works_media]]
  name = "triangle"
  id = "_UV-tv2FAo8"
  type = "youtube"
[[params.works_media]]
  name = "quartet"
  id = "C0FBNLy4NCM"
  type = "youtube"
[[params.works_media]]
  name = "apsis ii"
  id = "NNOv9wCXzMc"
  type = "youtube"
[[params.works_media]]
  name = "still motion"
  id = "O0tJMihak4U"
  type = "youtube"
[[params.works_media]]
  name = "tap"
  id = "588iNBZDJy0"
  type = "youtube"
[[params.works_media]]
  name = "November 15, 2019"
  album = "3748377265"
  track = "1472216924"
  type = "bandcamp"
[[params.works_media]]
  name = "if two things..."
  id = "8vEfSfQfbVg"
  type = "youtube"
[[params.works_media]]
  name = "circle"
  id = "462225324"
  type = "soundcloud"
[[params.works_media]]
  name = "it teaches us that it doesn't exist"
  id = "_sXEiksYkco"
  type = "youtube"

[[params.ananke_socials]]
  name = "instagram"
  url = "https://instagram.com/_ted_moore_"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/tedmoore"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/ted.moore.9619/"
[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCgCOXAIJJyU5cGMP8WXUedg"
# [[params.ananke_socials]]
#   name = "twitter"
#   url = "https://twitter.com/ted_moore"
[[params.ananke_socials]]
  name = "bandcamp"
  url = "https://tedmoore.bandcamp.com/"
  color = "#4A9FBF"
[[params.ananke_socials]]
  name = "soundcloud"
  url = "https://www.soundcloud.com/tedmoore"
  color = "#ed612b"

[menu]
[[menu.main]]
  name = 'works'
  weight = 1
  url = '/works/'
[[menu.main]]
  name = 'installations'
  weight = 2
  url = '/installations/'
[[menu.main]]
  name = 'improv'
  weight = 3
  url = '/improv/'
[[menu.main]]
  name = 'releases'
  weight = 4
  url = '/releases/'
[[menu.main]]
  name = 'theater/dance'
  url = '/theater-dance/'
  weight = 5
[[menu.main]]
  name = 'research/software'
  url = '/research/'
  weight = 6
[[menu.main]]
  name = 'about/contact'
  url = '/about-contact/'
  weight = 7
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# WORKS PAGE LIST ORDER

[[params.works_order]]
  name = 'saccades'
[[params.works_order]]
  name = 'arco'
[[params.works_order]]
  name = 'quartet'
[[params.works_order]]
  name = 'triangle'
[[params.works_order]]
  name = 'nand'
[[params.works_order]]
  name = 'tap'
[[params.works_order]]
  name = 'fold'
[[params.works_order]]
  name = 'apsis-ii'
[[params.works_order]]
  name = 'circle'
[[params.works_order]]
  name = 'still-motion'
[[params.works_order]]
  name = 'patina'
[[params.works_order]]
  name = 'it-teaches-us'
[[params.works_order]]
  name = 'feathermucker'
[[params.works_order]]
  name = 'solstice-orrery'
[[params.works_order]]
  name = 'noise-gate'
[[params.works_order]]
  name = 'apsis'
[[params.works_order]]
  name = 'hollow'
[[params.works_order]]
  name = 'if-two-things'
[[params.works_order]]
  name = 'eclipse'
[[params.works_order]]
  name = 'feed'
[[params.works_order]]
  name = 'alloy'
[[params.works_order]]
  name = 'for-line-upon-line'
[[params.works_order]]
  name = 'still-motion-b'
[[params.works_order]]
  name = 'hold'
[[params.works_order]]
  name = 'the-curve-is-exponential'
[[params.works_order]]
  name = 'transliteration'
[[params.works_order]]
  name = 'column'
[[params.works_order]]
  name = 'crunch'
[[params.works_order]]
  name = 'shadow'
[[params.works_order]]
  name = 'appetite'
[[params.works_order]]
  name = 'thread-fork-thread'
[[params.works_order]]
  name = 'persephone'
[[params.works_order]]
  name = 'samara'
[[params.works_order]]
  name = 'feedback-v'
[[params.works_order]]
  name = 'leviathan'
[[params.works_order]]
  name = 'gilgamesh-enkidu'
[[params.works_order]]
  name = 'fiery-walls'

# HOMEPAGE ORDER

[[params.homepage_order]]
  name = 'saccades'
[[params.homepage_order]]
  name = 'tap'
[[params.homepage_order]]
  name = 'improv'
[[params.homepage_order]]
  name = 'arco'
[[params.homepage_order]]
  name = 'aluminum-forest'
[[params.homepage_order]]
  name = 'triangle'
[[params.homepage_order]]
  name = 'quartet'
[[params.homepage_order]]
  name = 'nand'
[[params.homepage_order]]
  name = 'it-teaches-us'
[[params.homepage_order]]
  name = 'still-motion'
[[params.homepage_order]]
  name = 'circle'
[[params.homepage_order]]
  name = 'attacksustainrelease'
[[params.homepage_order]]
  name = 'hollow'
[[params.homepage_order]]
  name = 'feathermucker'
[[params.homepage_order]]
  name = 'patina'
[[params.homepage_order]]
  name = 'binary-canary'
[[params.homepage_order]]
  name = 'shadow'
[[params.homepage_order]]
  name = 'noise-gate'
[[params.homepage_order]]
  name = 'flucoma'
[[params.homepage_order]]
  name = 'apsis'
[[params.homepage_order]]
  name = 'transliteration'
[[params.homepage_order]]
  name = 'DJII'
[[params.homepage_order]]
  name = 'hold'
[[params.homepage_order]]
  name = 'apsis-ii'
[[params.homepage_order]]
  name = 'for-line-upon-line'
[[params.homepage_order]]
  name = 'eclipse'
[[params.homepage_order]]
  name = 'fold'
[[params.homepage_order]]
  name = 'alloy'
[[params.homepage_order]]
  name = 'if-two-things'
[[params.homepage_order]]
  name = 'persephone'
[[params.homepage_order]]
  name = 'still-motion-b'
[[params.homepage_order]]
  name = 'solstice-orrery'
[[params.homepage_order]]
  name = 'appetite'
[[params.homepage_order]]
  name = 'serge'

# THEATER STUFF

[[params.theater_list]]
  Title = 'BODYTALK'
  Year = '2019'
  Description = 'Theater and Performing Arts Department, University of Chicago, Choreographed by Sophia Bell'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'The Broken Jug'
  Year = '2018'
  Description = 'Theater and Performing Arts Department, University of Chicago, Directed by Pirachula Chulanon'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Bluets'
  Year = '2017'
  Description = 'Music by Catherine Dalton'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'APPETITE'
  Year = '2017'
  Description = 'Ted Moore and Charles Campbell (Skewed Visions)'
  role = 'Sound Design, Video Design, and Performance'
  URL = '/works/appetite'
[[params.theater_list]]
  Title = 'June'
  Year = '2016'
  Description = 'Umbrella Collective'
  role = 'Composer'
  URL = 'https://www.umbrellaco.org/june-2016.html'
[[params.theater_list]]
  Title = 'These Are The Men'
  Year = '2015'
  Description = 'Umbrella Collective'
  role = 'Sound Designer'
  URL = 'https://www.umbrellaco.org/tatm-2015.html'
[[params.theater_list]]
  Title = 'PERSEPHONE'
  Year = '2014'
  Description = 'Choreography by Hannah Holman'
  role = 'Composer and Sound Designer'
  URL = '/works/persephone'
[[params.theater_list]]
  Title = 'Mineapolis Cubed'
  Year = '2014'
  Description = 'Directed by Eric F. Avery'
  role = 'Composer, Sound Designer, Installation Artist, and Performer'
  URL = 'none'
[[params.theater_list]]
  Title = 'HWY 57'
  Year = '2014'
  Description = 'Choreography by Blake Nellis'
  role = 'Composer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Rapture'
  Year = '2014'
  Description = 'Umbrella Collective'
  role = 'Composer and Sound Designer'
  URL = 'https://www.umbrellaco.org/rapture-2014.html'
[[params.theater_list]]
  Title = 'Body House'
  Year = '2014'
  Description = 'Written by Megan Clark Directed by Gwethalyn Williams'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'These Are The Men (workshop)'
  Year = '2014'
  Description = 'Umbrella Collective'
  role = 'Sound Designer'
  URL = 'https://www.umbrellaco.org/tatm-workshop-2014.html'
[[params.theater_list]]
  Title = 'Minneapolis Cubed'
  Year = '2014'
  Description = 'with Eric F. Avery at the Northern Spark Festival'
  role = 'Sound Designer, Composer, Installation Artist, & Performer'
  URL = 'https://www.umbrellaco.org/tatm-workshop-2014.html'
[[params.theater_list]]
  Title = 'Junk Song'
  Year = '2013'
  Description = 'Nimbus Theater'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Leaves'
  Year = '2013'
  Description = 'Umbrella Collective'
  role = 'Music Director and Guitarist'
  URL = 'https://www.umbrellaco.org/leaves-2013.html'
[[params.theater_list]]
  Title = 'Rain Follows the Plow'
  Year = '2013'
  Description = 'Umbrella Collective'
  role = 'Composer and Sound Designer'
  URL = 'https://www.umbrellaco.org/rainfollows-2013.html'
[[params.theater_list]]
  Title = 'Rules of Love'
  Year = '2013'
  Description = 'Minnesota Fringe Festival'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Emma Woodhouse is Not a Bitch'
  Year = '2013'
  Description = 'Umbrella Collective'
  role = 'Sound Designer'
  URL = 'https://www.umbrellaco.org/emma-2013.html'
[[params.theater_list]]
  Title = 'Care Enough'
  Year = '2012'
  Description = 'Umbrella Collective'
  role = 'Composer and Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'The View From here'
  Year = '2012'
  Description = 'Nautilus Music-Theater'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Europera 5'
  Year = '2012'
  Description = 'by John Cage, with Nautilus Music-Theater'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Since the Kids are Gone'
  Year = '2012'
  Description = 'Freshwater Theater'
  role = 'Sound Designer'
  URL = 'none'
[[params.theater_list]]
  Title = 'Joan of Arc'
  Year = '2011'
  Description = 'Nautilus Music-Theater'
  role = 'Sound Designer'
  URL = 'none'

# Theater page media order

[[params.theater_media]]
  Title = "APPETITE"
  info = "(excerpts)"
  Year = "2017"
  type = "vimeo"
  id = "221813599"
[[params.theater_media]]
  Title = "PERSEPHONE"
  Year = "2014"
  type = "youtube"
  id = "UPwYeKGpeEI"
[[params.theater_media]]
  Title = "Body House"
  Year = "2014"
  type = "image"
  path = "/images/body-house.jpg"