baseURL = 'http://www.tedmooremusic.com/'
languageCode = 'en-us'
title = "Ted Moore | Composer, Improviser, Multimedia Artist"
copyright = "Ted Moore. All Rights Reserved."
theme = ["gohugo-theme-ananke"]
paginate = 99

[params]
  # menu_classes = 'helvetica neue'
  # menu_classes = 'avenir next'
  menu_classes = 'system sans-serif'
  # menu_classes = 'garamond'
  # menu_classes = 'roboto'
  # body_classes = 'roboto'
  body_classes = 'avenir next'
  # body_classes = 'helvetica neue'
  # body_classes = 'avenir'
  # body_classes = "avenir bg-near-white"
  
  # post_content_classes = 'helvetica neue'
  post_content_classes = 'avenir next'

[[params.works_media]]
  name = "triangle"
  id = "_UV-tv2FAo8"
  type = "youtube"
[[params.works_media]]
  name = "apsis ii"
  id = "NNOv9wCXzMc"
  type = "youtube"
[[params.works_media]]
  name = "still motion"
  id = "O0tJMihak4U"
  type = "youtube"
[[params.works_media]]
  name = "tap"
  id = "588iNBZDJy0"
  type = "youtube"
[[params.works_media]]
  name = "November 15, 2019"
  album = "3748377265"
  track = "1472216924"
  type = "bandcamp"
[[params.ananke_socials]]
  name = "instagram"
  url = "https://instagram.com/_ted_moore_"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/tedmoore"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/ted.moore.9619/"
[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCgCOXAIJJyU5cGMP8WXUedg"
[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/ted_moore"
[[params.ananke_socials]]
  name = "bandcamp"
  url = "https://tedmoore.bandcamp.com/"
  color = "#4A9FBF"
[[params.ananke_socials]]
  name = "soundcloud"
  url = "https://www.soundcloud.com/tedmoore"
  color = "#ed612b"
[menu]
[[menu.main]]
  name = 'works'
  weight = 1
  url = '/works/'
[[menu.main]]
  name = 'installations'
  weight = 2
  url = '/installations/'
[[menu.main]]
  name = 'releases'
  weight = 4
  url = '/releases/'
[[menu.main]]
  name = 'improv'
  weight = 3
  url = '/improv/'
[[menu.main]]
  name = 'research/software'
  url = '/research/'
  weight = 6
[[menu.main]]
  name = 'theater/dance'
  url = '/theaterdance/'
  weight = 5
[[menu.main]]
  name = 'about/contact'
  url = '/aboutcontact/'
  weight = 7
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# WORKS PAGE LIST ORDER

[[params.works_order]]
  name = 'noise-gate'
[[params.works_order]]
  name = 'quartet'
[[params.works_order]]
  name = 'triangle'
[[params.works_order]]
  name = 'tap'
[[params.works_order]]
  name = 'apsis-ii'
[[params.works_order]]
  name = 'for-line-upon-line'
[[params.works_order]]
  name = 'circle'
[[params.works_order]]
  name = 'still-motion'
[[params.works_order]]
  name = 'hold'
[[params.works_order]]
  name = 'feed'
[[params.works_order]]
  name = 'column'
[[params.works_order]]
  name = 'patina'
[[params.works_order]]
  name = 'it-teaches-us'
[[params.works_order]]
  name = 'hollow'
[[params.works_order]]
  name = 'crunch'
[[params.works_order]]
  name = 'feathermucker'
[[params.works_order]]
  name = 'solstice-orrery'
[[params.works_order]]
  name = 'shadow'
[[params.works_order]]
  name = 'appetite'
[[params.works_order]]
  name = 'if-two-things'
[[params.works_order]]
  name = 'apsis'
[[params.works_order]]
  name = 'eclipse'
[[params.works_order]]
  name = 'thread-fork-thread'
[[params.works_order]]
  name = 'the-curve-is-exponential'
[[params.works_order]]
  name = 'samara'
[[params.works_order]]
  name = 'feedback-v'
[[params.works_order]]
  name = 'persephone'
[[params.works_order]]
  name = 'transliteration'
[[params.works_order]]
  name = 'leviathan'
[[params.works_order]]
  name = 'fiery-walls'

# HOMEPAGE ORDER

[[params.homepage_order]]
  name = 'tap'
[[params.homepage_order]]
  name = 'improv'
[[params.homepage_order]]
  name = 'aluminum-forest'
[[params.homepage_order]]
  name = 'triangle'
[[params.homepage_order]]
  name = 'quartet'
[[params.homepage_order]]
  name = 'it-teaches-us'
[[params.homepage_order]]
  name = 'still-motion'
[[params.homepage_order]]
  name = 'circle'
[[params.homepage_order]]
  name = 'attacksustainrelease'
[[params.homepage_order]]
  name = 'hollow'
[[params.homepage_order]]
  name = 'feathermucker'
[[params.homepage_order]]
  name = 'patina'
[[params.homepage_order]]
  name = 'shadow'
[[params.homepage_order]]
  name = 'noise-gate'
[[params.homepage_order]]
  name = 'apsis'
[[params.homepage_order]]
  name = 'transliteration'
[[params.homepage_order]]
  name = 'DJII'
[[params.homepage_order]]
  name = 'hold'
[[params.homepage_order]]
  name = 'apsis-ii'
[[params.homepage_order]]
  name = 'for-line-upon-line'
[[params.homepage_order]]
  name = 'eclipse'
[[params.homepage_order]]
  name = 'if-two-things'
[[params.homepage_order]]
  name = 'solstice-orrery'
[[params.homepage_order]]
  name = 'appetite'
[[params.homepage_order]]
  name = 'spacer'
[[params.homepage_order]]
  name = 'spacer'
[[params.homepage_order]]
  name = 'serge'