baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Ted Moore | Composer, Improviser, Multimedia Artist, Creative Coder, Educator"
theme = "gohugo-theme-ananke"
featured_image = "Ted Moore - credit Ben Semisch 01.jpg"
paginate = 99
googlefonts = "http://fonts.googleapis.com/css?family=Itim|Limelight"

[params]
  # site_logo = "images/Ted Moore pc Brian Fancher.jpg"
  # menu_classes = 'helvetica neue'
  menu_classes = 'avenir next'
  # menu_classes = 'garamond'
  # menu_classes = 'roboto'
  # body_classes = 'roboto'
  body_classes = 'avenir next'
  # body_classes = 'helvetica neue'
  # body_classes = 'avenir'
  # body_classes = "avenir bg-near-white"
  
  # post_content_classes = 'helvetica neue'
  post_content_classes = 'avenir next'
  worksmedia = ['tap','triangle','apsis-ii']
[[params.ananke_socials]]
  name = "instagram"
  url = "https://instagram.com/_ted_moore_"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/tedmoore"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/ted.moore.9619/"
[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCgCOXAIJJyU5cGMP8WXUedg"
[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/ted_moore"
[[params.ananke_socials]]
  name = "bandcamp"
  url = "https://tedmoore.bandcamp.com/"
  color = "#4A9FBF"
[[params.ananke_socials]]
  name = "soundcloud"
  url = "https://www.soundcloud.com/tedmoore"
  color = "#ed612b"
[menu]
[[menu.main]]
  name = 'works'
  weight = 1
  url = '/works/'
[[menu.main]]
  name = 'installations'
  weight = 2
  url = '/installations/'
[[menu.main]]
  name = 'releases'
  weight = 4
  url = '/releases/'
[[menu.main]]
  name = 'improv'
  weight = 3
  url = '/improv/'
[[menu.main]]
  name = 'research/software'
  url = '/research/'
  weight = 6
[[menu.main]]
  name = 'theater/dance'
  url = '/theaterdance/'
  weight = 5
[[menu.main]]
  name = 'about/contact'
  url = '/aboutcontact/'
  weight = 7
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
